---
resources:
  - name: app-code
    type: git
    source:
      uri: https://github.com/pjcalvo/scrapy_crawler.git
      branch: master

  - name: scrapy-image
    type: docker-image
    source:
      email: pjcalvov@gmail.com
      username: pjcalvo
      password: minovia
      repository: pjcalvo/scrapy

jobs:
  - name: tabernacle-choir
    public: true
    serial: true
    plan:
      - get: app-code
        trigger: true
      - put: scrapy-image
        params: 
          build: app-code/ci 
      - task: run
        config:
          platform: linux
          image_resource:
            type: scrapy-image
            source:
              repository: pjcalvo/scrapy
          run:
            path: sh
        params:
          DYNACONF_START_URLS: '@json ["http://google.com"]'
        



